### ISSUE TITLE
Alternative Secret Store

### ISSUE THREAD

**Issue by klnusbaum** [abhinav/git-spice#294]
No matter what auth method I try, I keep getting the following error:
```
FTL gs: The name org.freedesktop.secrets was not provided by any .service files
```

I'm running in a headless docker container, without GNOME or KDE installed. I'm unaware of any headless options for a org.freedesktop.secret service.

It would nice if there was some way to store github tokens/credentials without a secret store (or point in the documentation to a headless secret store if we can find one).

One alternative might be storing the token in a dedicated file in $XDG_DATA_HOME, i.e. maybe `~/.local/share/git-spice/github-token`, with the perms set to 400 so only the user can read it.

**Comment by abhinav** [comment]
Yeah, this is valid. Putting it in [UserConfigDir](https://pkg.go.dev/os#UserConfigDir) seems to make sense.
400 won't do—that's read-only. We need write permissions too: 600.
This issue was reported in #293 first, so closing in favor of that.
