### ISSUE TITLE
Feature Request: Gitlab Support

### ISSUE THREAD

**Issue by entropitor** [abhinav/git-spice#348]
It would be nice if git-spice also supported creating Merge Requests in GitLab

If it's not supported, it would also already be helpful to allow pushing all branches in the stack after restacking

**Comment by abhinav** [comment]
Hello, thanks for the feature request.
While I don't have plans to implement this myself in the near future, I would welcome a PR implementing it, and would be willing to work with the contributor to get the PR merged.

For those looking to add GitLab or other code forges, there's space specifically carved out in the architecture to permit this without intrusive code changes:

- For a new forge, one must implement the [Forge interface](https://github.com/abhinav/git-spice/blob/4fb05882490889cdacf5886c985f63dec2136eb2/internal/forge/forge.go) and [register it](https://github.com/abhinav/git-spice/blob/4fb05882490889cdacf5886c985f63dec2136eb2/internal/forge/forge.go#L30).
- Forges can record arbitrary metadata about the review unit as long as they tell the system [how to serialize and deserialize it](https://github.com/abhinav/git-spice/blob/4fb05882490889cdacf5886c985f63dec2136eb2/internal/forge/forge.go#L91-L95). For example, the GitHub forge actually records the [PR number, the PR GraphQL ID](https://github.com/abhinav/git-spice/blob/4fb05882490889cdacf5886c985f63dec2136eb2/internal/forge/github/change_meta.go#L80-L88), and [information about the stack navigation comment](https://github.com/abhinav/git-spice/blob/4fb05882490889cdacf5886c985f63dec2136eb2/internal/forge/github/comment.go#L12-L15).
- For authentication, again, forges implement [the authentication flow](https://github.com/abhinav/git-spice/blob/4fb05882490889cdacf5886c985f63dec2136eb2/internal/forge/forge.go#L102) and [how to serialize and deserialize the authentication token for secure storage](https://github.com/abhinav/git-spice/blob/4fb05882490889cdacf5886c985f63dec2136eb2/internal/forge/forge.go#L106-L114).

All GitHub specific details are implemented in the [forge/github package](https://github.com/abhinav/git-spice/tree/4fb05882490889cdacf5886c985f63dec2136eb2/internal/forge/github) for reference.

**Comment by abhinav** [comment]
RE: this:

> If it's not supported, it would also already be helpful to allow pushing all branches in the stack after restacking

That's possible today! You can use the [`--no-publish` flag of the `submit` commands](https://abhinav.github.io/git-spice/cli/reference/#gs-stack-submit) to push branches without creating PRs. If you have trouble using that with GitLab or non-GitHub forges, please let me know (preferably in a different issue), and we can get that fixed up.
