### ISSUE TITLE
Logout doesn't actually log me out

### ISSUE THREAD

**Issue by klnusbaum** [abhinav/git-spice#352]
I'm currently using a github classic token to interact with git spice. Today, I wanted to log out and log back in using a different auth method. The following happened:

```
2024-08-21 11:37:16 PDT entities@kdevenv # gs auth logout
INF github: logged out
2024-08-21 11:37:23 PDT entities@kdevenv # gs auth login
ERR Use --refresh to force a refresh of the authentication token
FTL gs: github: already logged in
```

It appears that logging me out didn't actually log me out.

Additional info, config seems to be empty:
```
2024-08-21 11:40:09 PDT kurtis@kdevenv # ls -alh ~/.config/git-spice 
total 8.0K
drwx------  2 kurtis kurtis 4.0K Aug 21 11:37 .
drwxr-xr-x 16 kurtis kurtis 4.0K Aug  7 13:31 ..
```

Github token is not set:
```
2024-08-21 11:40:16 PDT kurtis@kdevenv # echo $GITHUB_TOKEN

2024-08-21 11:41:16 PDT kurtis@kdevenv #
```

**Comment by abhinav** [comment]
This is strange; that the file was deleted confirms that we logged out.
Does the issue persist, or was it one time?
(I'm guessing at the possibility of outdated storage, and whether logging out and logging in fixed it.)

**Comment by klnusbaum** [comment]
yea, strangely, things seem to be working now. I'm gonna close this. If I can reproduce it again, I'll try to grab some more info.
