### ISSUE TITLE
Git spice uses incorrect user for pr creation

### ISSUE THREAD

**Issue by klnusbaum** [abhinav/git-spice#367]
Sometimes (I'm not sure what triggers this), when I do `gs branch submit -c` a PR is opened, but one of our organizations bots is listed as the author (instead of me). I'm not sure if the problem is originating when I do `gs branch track`, or when I do `gs branch submit`. It may be related to the parent commit as well. I noticed that, at least in the most recent case, the bot was the author of the last commit on `master` which my commit was based off of.

```
2024-08-29 13:49:43 PDT environments@kdevenv # gs --version
git-spice 0.5.1 (559a706fcc1cd49df68cc9aafc384877e5981a6d 2024-08-28T05:19:11Z)
Copyright (C) 2024 Abhinav Gupta
  <https://github.com/abhinav/git-spice>
This program comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see source for details.
```

**Comment by klnusbaum** [comment]
Additional info:

The bot appears to be listed as the PR author, where as I'm listed as the commit author
Auth method is App I __think__

**Comment by abhinav** [comment]
To verify whether the authentication method is App or OAuth, you can check the saved token:
If it starts with `ghu_`, it's a GitHub App token, and `gho_` for OAuth.
On macOS, you can run the following command to see the token:

```
security find-generic-password -s 'git-spice:https://github.com' -w | cut -d':' -f2 | base64 -d
```

On Linux, if you don't have a secure keychain, check inside `$HOME/.config/git-spice/secrets.json`.

**Comment by klnusbaum** [comment]
It looks like the culprit is a `.envrc` file in one of the subdirectories. If you issue a `gs` command in the wrong context, it picks up a `GITHUB_TOKEN` variable for our bot. I think we can find a way to solve this on our own. If it turns out we need something from git spice I'll open a new issue.
