### ISSUE TITLE
Cached PR template does not update after remote file changed

### ISSUE THREAD

**Issue by messense** [abhinav/git-spice#369]
I've updated `pull_request_template.md` in trunk of remote git repository, but `git-spice` still uses the old cached template when submitting stacks.

**Comment by abhinav** [comment]
Hey, just to narrow this down: Is the branch you're submitting from restacked on top of trunk?

**Comment by messense** [comment]
Yes.

**Comment by abhinav** [comment]
Follow up: Is trunk fully synced?
If not, that would explain why it's using the old cache key because right now, it checks `$trunk`, not `origin/$trunk`, so even if an update to the template is merged to trunk, and you've fetched trunk, the local ref `$trunk` is behind and the cache is seeing the wrong version.
Easily fixable, but I want to make sure that's what you're seeing.

**Comment by abhinav** [comment]
If the above is the issue, then #370 should fix this.

**Comment by messense** [comment]
> Is trunk fully synced?

I think so, I've run `git pull` on my local checkout of trunk branch and also run `gs repo sync` again.

**Comment by abhinav** [comment]
Oh, `origin/$trunk` was in sync? That doesn't sound right.
Would you be able to try with #370? It's merged on main, but you'd have to [build from source](https://abhinav.github.io/git-spice/start/install/#build-from-source).
(And if the issue still persists: what is the path to the template file?)

**Comment by messense** [comment]
> The other thing I'm guessing could be wrong here is that the template file name is lower case, and right now, git-spice only checks upper-case names (PULL_REQUEST_TEMPLATE).

yes, the file name is indeed lower case: `.github/pull_request_template.md`

**Comment by abhinav** [comment]
Aha! That's it! Fix incoming!

**Comment by abhinav** [comment]
Alright, https://github.com/abhinav/git-spice/pull/371 should take care of it.

**Comment by messense** [comment]
Thanks for the quick fix! v0.5.2 works fine now.
