### ISSUE TITLE
Feature Request: `--fill` option for `gs stack submit`

### ISSUE THREAD

**Issue by klnusbaum** [abhinav/git-spice#378]
The `gs branch submit` command has the `--fill` flag that uses the commit message for the PR title and content. It would be nice if we had a similar flag for `gs stack submit` so I could just use the commit messages of each of my PRs.

**Comment by abhinav** [comment]
This already exists and should work?

<img width="629" alt="image" src="https://github.com/user-attachments/assets/9d84f5db-9414-4920-bea3-9f18ec698f43">

**Comment by abhinav** [comment]
These flags are shared across all submit commands:

https://github.com/abhinav/git-spice/blob/0e77118543501515b96b92967e29d6cdb044b134/branch_submit.go#L22-L31

**Comment by klnusbaum** [comment]
wtf. I must be blind. I swear I looked and didn't see the option. But it's there now. Sorry for the noise.
