### ISSUE TITLE
 get repository ID: Could not resolve to a Repository with the name

### ISSUE THREAD

**Issue by markalanevans** [abhinav/git-spice#437]
Running on windows.

just created my first branch. then I try to do a ```gs branch submit``` and I get:

``` get repository ID: Could not resolve to a Repository with the name 'MyCo\MyProj'```

What do I do?

**Comment by abhinav** [comment]
@markalanevans Thanks for the issue.
That response is coming from the GitHub API, specifically from here:

https://github.com/abhinav/git-spice/blob/af24094feeb0c54831d87c3add03b33e9c99baca/internal/forge/github/repository.go#L32-L42

It's just making the following GraphQL qurey:

```graphl
query {
  repository(owner: "MyCo", name: "MyProj") { id }
}
````

Are you sure that the API token you're using has access to this repository?

(Related: We can probably look at the error code and provide a more useful error message. I'm going to look into that separaetly.)

**Comment by markalanevans** [comment]
That was the clue. I had done the Github App Install but I had confused it with Github Desktop.

So i gs auth logout and then    "gs auth login" and created a personal token.

**Comment by abhinav** [comment]
Excellent! Confirming that fixed it?

I'm going to leave this issue open until I'm able to get some more information out in that error message.

**Comment by markalanevans** [comment]
Yes. 
Confirmed.

And thank you! I'm excited to test out the stacked PRs.
