### ISSUE TITLE
Add `--no-edit` to `rebase continue`

### ISSUE THREAD

**Issue by gr4cza** [abhinav/git-spice#503]
Most of the time, when I have to resolve a conflict during a rebase, I don’t want to edit the commit message. 
It would be really nice if we could add `--no-edit` to `rebase --continue`, similar to `commit amend`. 
It could even be an opt-in config to make this the default behaviour.

**Comment by abhinav** [comment]
This makes sense.

Note that `git rebase --continue` itself doesn't have a `--no-edit` mode, so if we have this flag, it'll have to temporarily set `core.editor` to a no-op editor (e.g. `git -c core.editor=true rebase --continue`).
